name: multilingual
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #* localization
  flutter_localizations: #* Add this package for localization
    sdk: flutter
  intl: ^0.17.0

  #* Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #* state management
  flutter_bloc: ^8.1.3

  #* local storage
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  generate: true #* add this line for localization (make true if want to generate localiztion file automatically on save)
  uses-material-design: true

flutter_intl:
  enabled: true
